#!/bin/bash
# ───────────────────────────────────────────────
# Purpose: Expand userdata partition, extract /user-data, update fstab, then reboot
# ───────────────────────────────────────────────
set -e

echo "🧠 Starting pre-extract setup..."

# 1. Install required packages
echo "📦 Installing required packages..."
sudo apt update -y
sudo apt install -y cloud-guest-utils vim modemmanager ppp

# 2. Detect root partition and parent device correctly
echo "🔍 Detecting root device..."
ROOT_PART=$(findmnt -n -o SOURCE /)
echo "→ Root partition: $ROOT_PART"

# Get parent block device name (e.g. mmcblk1, sda, nvme0n1)
ROOT_BASE=$(lsblk -no pkname "$ROOT_PART" | head -n1)
ROOT_DEV="/dev/$ROOT_BASE"
echo "→ Root device detected: $ROOT_DEV"

# 3. Determine correct partition 4 path (handles mmcblk, nvme, sd)
if [[ "$ROOT_BASE" == mmcblk* || "$ROOT_BASE" == nvme* ]]; then
    PART4="${ROOT_DEV}p4"
else
    PART4="${ROOT_DEV}4"
fi
echo "→ Target partition: $PART4"

# 4. Grow partition 4 and resize filesystem
echo "📈 Growing and resizing $PART4..."
if sudo growpart "$ROOT_DEV" 4; then
    sudo resize2fs "$PART4"
    sync
else
    echo "⚠️ growpart failed (maybe already full size or invalid partition)"
fi

# 5. Extract user-data archive
if [ -f /user-data/user-data.tar.gz ]; then
    echo "📦 Extracting /user-data/user-data.tar.gz..."
    sudo tar -xvzf /user-data/user-data.tar.gz
else
    echo "⚠️ /user-data/user-data.tar.gz not found, skipping extraction."
fi

# 6. Write /etc/fstab dynamically based on detected device
echo "🧾 Writing /etc/fstab..."
sudo bash -c "cat <<EOF > /etc/fstab
# Do not direct edit this file, this file was generated from run-this-before-extract-user-data.sh
${ROOT_DEV}p3 / ext4 defaults,noatime,commit=120,errors=remount-ro 0 1
${ROOT_DEV}p1 /boot ext4 defaults,ro 0 2
${PART4} /user-data ext4 defaults,noatime,commit=120,errors=remount-ro 0 2
/user-data/root /root none bind 0 0
/user-data/home /home none bind 0 0
tmpfs /tmp tmpfs defaults,nosuid 0 0
EOF"

# 7. Rename boot ENV file from armbianEnv.txt to hopeEnv.txt
echo "=== Remounting /boot as read-write ==="
sudo mount -o remount,rw /boot || sudo remount-boot-rw || true

BOOTCMD="/boot/boot.cmd"

echo "=== Writing new Hope-OS boot.cmd ==="
sudo tee "$BOOTCMD" > /dev/null << 'EOF'
# DO NOT EDIT THIS FILE
#
# Please edit /boot/hopeEnv.txt to set supported parameters
#

setenv load_addr "0x48000000"
setenv overlay_error "false"
# default values
setenv rootdev "/dev/mmcblk0p1"
setenv verbosity "1"
setenv console "both"
setenv bootlogo "false"
setenv rootfstype "ext4"
setenv docker_optimizations "on"
setenv earlycon "off"

echo "Boot script loaded from ${devtype} ${devnum}"

echo "Testing for existence ${devtype} ${devnum} ${prefix}hopeEnv.txt ..."
if test -e ${devtype} ${devnum} ${prefix}hopeEnv.txt; then
        echo "Found ${devtype} ${devnum} ${prefix}hopeEnv.txt - loading ${devtype} ${devnum} ${load_addr} ${prefix}hopeEnv.txt ..."
        load ${devtype} ${devnum} ${load_addr} ${prefix}hopeEnv.txt
        echo "Loaded environment from ${devtype} ${devnum} ${prefix}hopeEnv.txt into ${load_addr} filesize ${filesize}..."
        echo "Importing into environment ..."
        env import -t ${load_addr} ${filesize}
        echo "hopeEnv.txt imported into environment"
fi

if test "${logo}" = "disabled"; then setenv logo "logo.nologo"; fi

if test "${console}" = "display" || test "${console}" = "both"; then setenv consoleargs "console=tty1"; fi
if test "${console}" = "serial" || test "${console}" = "both"; then setenv consoleargs "console=ttyS2,1500000 ${consoleargs}"; fi
if test "${earlycon}" = "on"; then setenv consoleargs "earlycon ${consoleargs}"; fi
if test "${bootlogo}" = "true"; then
        setenv consoleargs "splash plymouth.ignore-serial-consoles ${consoleargs}"
else
        setenv consoleargs "splash=verbose ${consoleargs}"
fi

# get PARTUUID of first partition on SD/eMMC the boot script was loaded from
if test "${devtype}" = "mmc"; then part uuid mmc ${devnum}:${distro_bootpart} partuuid; fi

setenv bootargs "root=${rootdev} rootwait rootfstype=${rootfstype} ${consoleargs} consoleblank=0 loglevel=${verbosity} ubootpart=${partuuid} usb-storage.quirks=${usbstoragequirks} ${extraargs} ${extraboardargs}"

if test "${docker_optimizations}" = "on"; then setenv bootargs "${bootargs} cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory"; fi

load ${devtype} ${devnum}:${distro_bootpart} ${ramdisk_addr_r} ${prefix}uInitrd
load ${devtype} ${devnum}:${distro_bootpart} ${kernel_addr_r} ${prefix}Image

load ${devtype} ${devnum}:${distro_bootpart} ${fdt_addr_r} ${prefix}dtb/${fdtfile}
fdt addr ${fdt_addr_r}
fdt resize 65536
for overlay_file in ${overlays}; do
        if load ${devtype} ${devnum}:${distro_bootpart} ${load_addr} ${prefix}dtb/rockchip/overlay/${overlay_prefix}-${overlay_file}.dtbo; then
                echo "Applying kernel provided DT overlay ${overlay_prefix}-${overlay_file}.dtbo"
                fdt apply ${load_addr} || setenv overlay_error "true"
        elif load ${devtype} ${devnum}:${distro_bootpart} ${load_addr} ${prefix}dtb/rockchip/overlay/${overlay_file}.dtbo; then
                echo "Applying kernel provided DT overlay ${overlay_file}.dtbo"
                fdt apply ${load_addr} || setenv overlay_error "true"
        fi
done
for overlay_file in ${user_overlays}; do
        if load ${devtype} ${devnum}:${distro_bootpart} ${load_addr} ${prefix}overlay-user/${overlay_file}.dtbo; then
                echo "Applying user provided DT overlay ${overlay_file}.dtbo"
                fdt apply ${load_addr} || setenv overlay_error "true"
        fi
done
if test "${overlay_error}" = "true"; then
        echo "Error applying DT overlays, restoring original DT"
        load ${devtype} ${devnum}:${distro_bootpart} ${fdt_addr_r} ${prefix}dtb/${fdtfile}
else
        if test -e ${devtype} ${devnum}:${distro_bootpart} ${prefix}dtb/rockchip/overlay/${overlay_prefix}-fixup.scr; then
                load ${devtype} ${devnum}:${distro_bootpart} ${load_addr} ${prefix}dtb/rockchip/overlay/${overlay_prefix}-fixup.scr
                echo "Applying kernel provided DT fixup script (${overlay_prefix}-fixup.scr)"
                source ${load_addr}
        fi
        if test -e ${devtype} ${devnum}:${distro_bootpart} ${prefix}fixup.scr; then
                load ${devtype} ${devnum}:${distro_bootpart} ${load_addr} ${prefix}fixup.scr
                echo "Applying user provided fixup script (fixup.scr)"
                source ${load_addr}
        fi
fi

echo "Trying 'kaslrseed' command... Info: 'Unknown command' can be safely ignored since 'kaslrseed' does not apply to all boards."
kaslrseed # @TODO: This gives an error (Unknown command ' kaslrseed ' - try 'help') on many devices since CONFIG_CMD_KASLRSEED is not enabled
booti ${kernel_addr_r} ${ramdisk_addr_r} ${fdt_addr_r}

# Recompile with:
# mkimage -C none -A arm -T script -d /boot/boot.cmd /boot/boot.scr
EOF

echo "=== Creating new boot.scr from boot.cmd ==="
sudo mkimage -C none -A arm -T script -d /boot/boot.cmd /boot/boot.scr

echo "=== Renaming armbianEnv.txt → hopeEnv.txt (if exists) ==="
if [ -f /boot/armbianEnv.txt ]; then
    sudo mv /boot/armbianEnv.txt /boot/hopeEnv.txt
    echo "Renamed successfully."
else
    echo "armbianEnv.txt not found. Skipping rename."
fi

echo "=== Sync filesystem ==="
sync

echo "=== DONE! Reboot to apply changes ==="

# 8. Self-remove
SCRIPT_PATH="$(realpath "$0")"
echo "🧹 Removing script: $SCRIPT_PATH"
sudo rm -f "$SCRIPT_PATH"

# 9. Reboot
echo "🔁 Rebooting system in 5 seconds..."
sleep 5
sudo reboot
