#!/bin/bash
# ============================================================
#  OCTIMUS-I Post-Build Finalizer
#  Steps:
#   1  Format recovery (p2) and userdata (p4) partitions
#   2  Update fstab inside rootfs (p3)
#   3  Inject all files from octimus-i-resources → userdata
# ============================================================

set -e

IMG_DIR="/build/os-boy/new-build/build/output/images"
SRC_DIR="/build/os-boy/new-build/build/octimus-i-resources"
MNT_ROOT="/mnt/rootfs"
MNT_USERDATA="/mnt/userdata"

# --- Step 1 – find latest image file ---
IMG_FILE=$(ls -t "${IMG_DIR}"/*.img "${IMG_DIR}"/*.raw 2>/dev/null | head -n 1)
if [[ -z "$IMG_FILE" ]]; then
    echo "❌ No image found in ${IMG_DIR}"
    exit 1
fi
echo "[🌱] Found image: $IMG_FILE"

# --- Step 2 – setup loop device ---
LOOP=$(losetup -fP --show "$IMG_FILE")
echo "[🌱] Loop device attached: $LOOP"
sleep 1

# ============================================================
#  PART 1 – Format Extra Partitions (recovery & userdata)
# ============================================================

if [ -b "${LOOP}p2" ]; then
    echo "[🪄] Formatting ${LOOP}p2 as ext4 (recovery)"
    mkfs.ext4 -F -L recovery "${LOOP}p2"
else
    echo "⚠️  Partition 2 not found (skipped)"
fi

if [ -b "${LOOP}p4" ]; then
    echo "[🪄] Formatting ${LOOP}p4 as ext4 (userdata)"
    mkfs.ext4 -F -L userdata "${LOOP}p4"
else
    echo "⚠️  Partition 4 not found (skipped)"
fi

# --- Rename all partition labels ---
echo "[✏️] Setting partition labels..."
[[ -b "${LOOP}p1" ]] && e2label "${LOOP}p1" boot || true
[[ -b "${LOOP}p2" ]] && e2label "${LOOP}p2" recovery || true
[[ -b "${LOOP}p3" ]] && e2label "${LOOP}p3" rootfs || true
[[ -b "${LOOP}p4" ]] && e2label "${LOOP}p4" userdata || true

sync
partprobe "$LOOP"
sleep 1

echo "[🔍] Partition table after formatting:"
lsblk "$LOOP" -o NAME,LABEL,SIZE,TYPE

# ============================================================
#  PART 2 – Update fstab in RootFS
# ============================================================

if [ -b "${LOOP}p3" ]; then
    echo "[🧠] Mounting rootfs (${LOOP}p3)..."
    mkdir -p "$MNT_ROOT"
    mount "${LOOP}p3" "$MNT_ROOT"

    echo "[🧾] Writing /etc/fstab..."
    cat << 'EOF' > "$MNT_ROOT/etc/fstab"
# Auto-generated by post-build script
/dev/mmcblk1p3 / ext4 defaults,noatime,commit=120,errors=remount-ro 0 1
/dev/mmcblk1p1 /boot ext4 defaults,ro 0 2
/dev/mmcblk1p4 /user-data ext4 defaults,noatime,commit=120,errors=remount-ro 0 2
#/user-data/root /root none bind 0 0
#/user-data/home /home none bind 0 0
tmpfs /tmp tmpfs defaults,nosuid 0 0
EOF

    mkdir -p "$MNT_ROOT/user-data"
    sync
    umount "$MNT_ROOT"
    echo "[✅] fstab updated successfully"
else
    echo "⚠️  Partition 3 (rootfs) not found! Skipped fstab update."
fi

echo "[🧩] Checking filesystems..."
e2fsck -y "${LOOP}p3" || true
[[ -b "${LOOP}p4" ]] && e2fsck -y "${LOOP}p4" || true

# ============================================================
#  PART 3 – Inject Resources into /userdata
# ============================================================

if [ -b "${LOOP}p4" ]; then
    echo "[📦] Mounting userdata (${LOOP}p4)..."
    mkdir -p "$MNT_USERDATA"
    mount "${LOOP}p4" "$MNT_USERDATA"

    FREE_SPACE=$(df -m --output=avail "$MNT_USERDATA" | tail -n 1)
    TOTAL_SIZE=$(du -cm "${SRC_DIR}" | tail -n 1 | awk '{print $1}')
    if (( FREE_SPACE < TOTAL_SIZE + 50 )); then
        echo "[⚠️] Warning: Only ${FREE_SPACE} MB free, source = ${TOTAL_SIZE} MB"
    fi

    echo "[🚚] Copying all files from ${SRC_DIR} → ${MNT_USERDATA}"
    cp -av "${SRC_DIR}/." "$MNT_USERDATA/"

    sync
    umount "$MNT_USERDATA"
    rmdir "$MNT_USERDATA"
    echo "[✅] Files successfully injected to /userdata"
else
    echo "⚠️  Partition 4 not found, skipping resource injection"
fi

# ============================================================
#  CLEANUP
# ============================================================

echo "[🌿] Cleaning up..."
losetup -d "$LOOP"
rmdir "$MNT_ROOT" 2>/dev/null || true

echo "[🎉] All steps completed successfully for: $IMG_FILE"

